### ISSUE TITLE
Transportation - how it might really work, and base size issues

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#11]
I've pulled this out into an issue so that we can carry on discussing it separately from the special abilities branch, and included all three relevant comments...

---

Eric:

As written, might this permit cases where players could have sacrificed some movement, but don't because the rules say they can put the units in base contact anyway - so they use that to get a 'free' gain?

In general, I feel like perhaps there should be some concept of not exceeding the 'calculated maximum move you could get from the transport plus the embarked unit in combination' -- even if this means you must move transport unit a bit less or something to compensate rather than adding on the width of the disembarked unit's base and thus going beyond the calculated maximum move.

If there is something in this, I'd be happy for us to create an issue to tackle this properly later - just wanted to raise the point and get your thoughts.

_Originally posted by @digi-brain in https://github.com/GameBrains/er-core/pull/8#r648571469_

**Comment by IJW-Wartrader** [comment]
> As written, might this permit cases where players could have sacrificed some movement, but don't because the rules say they can put the units in base contact anyway - so they use that to get a 'free' gain?

As far as I can see, this would require them to have a base longer than 5 cm. 

Don't forget that the unit is **already** sacrificing 5 cm of move just to be able to disembark. This is another reason why I automatically assumed that you 'deploy then measure' - as far as I was concerned, the unit had paid a movement penalty to get out, why would the unit have to pay a **second** movement penalty by measuring from the transport to 'move' out?

As a reminder, don't forget that what we currently have is already going to be regarded as a controversial rules change by some players, and if they've played 'deploy then measure' for a long time it's going to be unpopular, at best.

> In general, I feel like perhaps there should be some concept of not exceeding the 'calculated maximum move you could get from the transport plus the embarked unit in combination' -- even if this means you must move transport unit a bit less or something to compensate rather than adding on the width of the disembarked unit's base and thus going beyond the calculated maximum move.

My gut reaction is that this part of the map is marked 'Here be Dragons'. It's likely to be hard to write clear concise rules for, the overall subject is already controversial/generates lots of arguments, it's unlikely to get widespread support from the players (and that includes me), and it adds even more inconsistencies with Hitch. Or you apply it to Hitch as well, and screw over the Orks even more.

Paraphrasing...

'You know that unstoppable Battlefortress war engine that isn't slowed down at all when Da Boyz leap suicidally off the side?'
'Yer.'
'Well, it just slowed down by 4 cm because some of Da Boyz want to leap suicidally off the front instead of the side.'

P.S. In places where I'd normally use italics for emphasis I'm using bold on Github for consistency with the style guide.

_Originally posted by @IJW-Wartrader in https://github.com/GameBrains/er-core/pull/8#r648627497_

**Comment by IJW-Wartrader** [comment]
Eric:

>Don't forget that the unit is already sacrificing 5 cm of move just to be able to disembark.

I always rationalised the 5cm cost as a cost in **time** to embark/disembark, which seems reasonable and logical to me - not a 'compensation' for the width of the base, as you appear to see it. Though I can see that perhaps that makes sense from the point of view of game mechanics, but then why pay it twice?

But yeah, okay, let's skip this. The very fact that this part of the rules is controversial and creates arguments is exactly why I'm thinking that perhaps we could at least suggest 'ways to play this to make it more consistent or fair' -- but that could be in another section in future perhaps, especially as it might be hard to make concise, as you say.

It really irritates me when people 'conveniently' gain extra move for their units by virtue of the width of their base - so personally I tend to play it so that no individual unit can move farther in total than the maximum you can calculate that they should move. That seems the only fair way to me, and if that means moving your Battlefortress back a bit then so be it. If the Orks are massively disadvantaged in some way, then fix that rather than focus on loss of a gain that wasn't earned anyway.

But yes, different systems, different views. I've taken a view that seems the most consistent and fair to me.

I'll resolve this as 'nothing to do here', but if we do ever do a section for 'suggestions you can pick and choose for things that might otherwise be contentious or that don't render down to nice concise rules' then I think this is a contender for more attention!

_Originally posted by @digi-brain in https://github.com/GameBrains/er-core/pull/8#r648662960_

**Comment by IJW-Wartrader** [comment]
On to new stuff. And going back to italics for standard emphasis.

### Transportation Assumption

If an Infantry unit has Speed 10 cm and both embarks and disembarks in the same 'move', Hitch and Transport are functionally identical _from the point of view of the Infantry unit_. The Transport unit will get slowed down, but that's the only difference.

Everything related to transportation, for me, builds from that foundation.

---

> I always rationalised the 5cm cost as a cost in **time** to embark/disembark, which seems reasonable and logical to me - not a 'compensation' for the width of the base, as you appear to see it. Though I can see that perhaps that makes sense from the point of view of game mechanics, but then why pay it twice?

That's exactly my rationalisation for it as well! Both units have paid the time penalty (which is functionally identical to a distance penalty, within context), so why is a second penalty being paid?

---

> It really irritates me when people 'conveniently' gain extra move for their units by virtue of the width of their base - so personally I tend to play it so that no individual unit can move farther in total than the maximum you can calculate that they should move. That seems the only fair way to me, and if that means moving your Battlefortress back a bit then so be it. If the Orks are massively disadvantaged in some way, then fix that rather than focus on loss of a gain that wasn't earned anyway.

I _do_ understand your point about extra moves/distances, I have similar issues with 'daisy-chain' coherency in EA meaning that base size has a massive impact on how much a formation can spread out. Which is one of the reasons why I like the command radius in E40k as it makes base sizes far less critical, even with all the transportation issues we're discussing.

But. 

The idea of compensating for this by altering the distance _the Transport unit_ can move sets my teeth on edge, like fingernails down a blackboard. Especially for Battlefortresses, which aren't even part of the same detachment as the transported units. I see the reasoning in terms of fairness, but for me it's completely the wrong 'place' to add the extra level of abstraction.

---

### Proposal

Drawing all of this together, if we're going with the _hypothetical situation_ where we're reworking the transportation rules more drastically, and working from these principles:

- Hitch and Transport are functionally identical for the embarked units if they have Speed 10 cm and embark and disembark in the same 'move'.
- Units can always embark and disembark in one 'move' as long as they have Speed 10 cm or higher.
- Units can always embark/disembark if they have at least 5 cm of movement and are close enough to the Transport unit (aka disembarking on Overwatch orders).
- The size of the units' bases should have no effect on the overall limit of how far they can reach.

We can adapt and improve the EA rules for embarking and disembarking. Something like this, I'm using 'Transport' as shorthand for both Transport and Hitch:

- When you embark a unit, it must be completely within 5 cm of the Transport unit.
- When you disembark a unit, place it completely within 5 cm of the Transport unit. (Note, this also applies to destruction of Transport units.)

So a unit of Space Marines in a Rhino, making an Assault move, will:

1. Move the Rhino up to 25cm.
2. Disembark the Marine unit completely within 5 cm. (Total 'distance' is now 30 cm.)
3. Move the Marine unit 5 cm, or charge 15 cm. (Total 'distance' is now 35 cm or 45 cm.)

But if this is such a big issue in EA, why would it work in Remastered?

1. Transports in E40k/Remastered generally have a lower cap on transport capacity. An EA Orkeosaurus can transport 18 units (Transport 12, plus 6 Grots) and a Plague Tower 16, but the biggest capacity I'm aware of in E40k is 12 for a Hellbore and the Plague Tower is only 8.
2. All disembarking in EA happens _at the end of a move_. E40k doesn't have that restriction, so if there was a Transport unit with so many embarked units that they can't all disembark within 5 cm, some of them can disembark earlier in Transport unit's move. In effect, you fill up the 5 cm bubble around the Transport unit with disembarking units, and then extend the bubble back along the movement path.

**Comment by digi-brain** [comment]
Thanks for creating the issue and taking the time to copy the conversation across, nice one.

---

>If an Infantry unit has Speed 10 cm and both embarks and disembarks in the same 'move'

Yeah, I think I played it on the assumption that a Speed 10 cm unit can't embark and disembark in the same move (aside from edge case like charge perhaps), so my assumption differs from yours. I'm not sure how that changes all the other assumptions and ramifications, so off the top of my head I can't compare what pros/cons that might have as compared with your assumption.

---

>Both units have paid the time penalty (which is functionally identical to a distance penalty, within context), so why is a second penalty being paid?

As I see it, you pay once because you're embarking, and a second time because you're disembarking, and those things may happen in different turns. In this model it seems logical to pay twice to me. That's why I thought you viewed it as 'compensation for the width of the base' because then perhaps it'd make more sense to pay only once. Although that's also dependent on how you do embarkation and disembarkation -- if you embark units when they are within 5 cm (if you think the 5 cm payment should cover this) that's different to if you only embark units when they are in base contact (I do the latter).

---

> I have similar issues with 'daisy-chain' coherency in EA meaning that base size has a massive impact

Yup, totally with you there. In general I've played with a loose concept of 'what you could've done with the traditional 20 mm square bases', to even out these effects. Basically, act as though all your units were actually on 20 mm square bases for certain contentious things like 'daisy chain zone of control', how many units should fit into cover in a building, and so on. Obviously not a robust rule — just a rule of thumb to make certain things a bit more fair.

---

>The idea of compensating for this by altering the distance the Transport unit can move sets my teeth on edge, like fingernails down a blackboard. Especially for Battlefortresses, which aren't even part of the same detachment as the transported units. I see the reasoning in terms of fairness, but for me it's completely the wrong 'place' to add the extra level of abstraction.

Fair enough. I'm just inherently geared more towards fairness than other concerns, so I tend to accept other compromises or abstractions without too much worry as long as I perceive it to be more fair than the known alternatives.

Sometimes you can't have everything and a solution may mean that you have to make a choice — do you want a couple of extra Ork infantry units to reach combat, or do you want a couple of extra centimetres on your Battlefortress? Life and wargames are full of choices. But, everyone has different triggers for what grates on their nerves and what doesn't, so I'm not trying to say that my way is the only 'good' way.

---

All that said, from a quick skim your proposal seems sensible. I'll give it a closer look later.

**Comment by IJW-Wartrader** [comment]
> Thanks for creating the issue and taking the time to copy the conversation across, nice one.

Yeah, there was enough stuff in the conversation that referencing one post wasn't going to be useful!

---

> > If an Infantry unit has Speed 10 cm and both embarks and disembarks in the same 'move'
> 
> Yeah, I think I played it on the assumption that a Speed 10 cm unit can't embark and disembark in the same move (aside from edge case like charge perhaps)...

Note that I listed it in the assumptions for completeness, but it's specifically called out in the original Transport (x) text, 'It is possible for infantry to mount up, be transported to a new location and then dismount at a cost of 10cm movement to both the infantry and the transport.'.

This is another of the reasons why I defaulted to 'deploy then measure' for disembarking units, because the vast majority of Infantry in E40k have Speed 10 cm so they **must** be able to disembark in base contact after paying 5 cm to disembark.

---

> > Both units have paid the time penalty (which is functionally identical to a distance penalty, within context), so why is a second penalty being paid?
> 
> As I see it, you pay once because you're embarking, and a second time because you're disembarking, and those things may happen in different turns. In this model it seems logical to pay twice to me. That's why I thought you viewed it as 'compensation for the width of the base' because then perhaps it'd make more sense to pay only once. Although that's also dependent on how you do embarkation and disembarkation -- if you embark units when they are within 5 cm (if you think the 5 cm payment should cover this) that's different to if you only embark units when they are in base contact (I do the latter).

Crossed wires again. ;-)

Let's talk about disembarking and ignore embarking for now. I'll use 'Rhino' and 'Marines' (for a single unit) here because it's clearer and easier than typing out 'Transport unit' and 'Infantry unit' or 'embarked unit' every time.

A unit of Marines starts the Movement phase in a Rhino. The Rhino moves, and the Marines get out. The Marines and the Rhino both pay their 5 cm penalty for the Marines to disembark. If the disembarking Marines have to spend movement to 'move out' from the Rhino, the Marines are paying a _second_ cost for disembarking. And because of the bit from Transport (x) that I quoted above, you have to be able to disembark with 0 cm of remaining movement.

Coming back to embarkation, my default reading of the E40k rules, and how we played, was that the embarking Marines had to be in/reach base contact with the Rhino*, paid 5 cm of move, and were taken off the table. Disembarking was then the exact opposite - the Marines paid the 5 cm penalty, and were put back on the table in base contact with the Rhino.

*Whether that's because they started the move in contact, the embarking Marines moved to reach the Rhino (which would stop them from disembarking again), the Rhino moved into contact with the Marines, or a mix of both of them moving into contact.

**Comment by digi-brain** [comment]
>Note that I listed it in the assumptions for completeness, but it's specifically called out in the original Transport (x) text, 'It is possible for infantry to mount up, be transported to a new location and then dismount at a cost of 10cm movement to both the infantry and the transport.'.

>And because of the bit from Transport (x) that I quoted above, you have to be able to disembark with 0 cm of remaining movement.

That quote isn't really evidence for a particular interpretation in my view. It is so vague that your interpretation really depends on what presumptions you're already making.

Even when we presume or infer that they meant "in the same phase" or even "in the same single move" it doesn't necessarily follow that a unit that only has a 10 cm move can actually embark and disembark in a single move. Only that it costs 10 cm. You might still be required to pay the width of the base, which is what I assumed - so Speed 10 cm units can only embark and disembark in the same phase on March orders or when they charge in the Assault phase. While Speed 15cm units could actually embark and disembark in the same single move on Normal orders because they have 5cm remaining to pay for the width of their bases.

I'm not saying that my interpretation is right, and I'm interested to see how your interpretation pans out. I'm just saying that in itself that particular sentence doesn't seem to detract from my interpretation.

However, now that I think about it like that, I can see that my interpretation creates an even bigger difference between Speed 10 cm and Speed 15 cm infantry, which might have game balance and relative points cost effectiveness issues that point more in favour of your interpretation.

>A unit of Marines starts the Movement phase in a Rhino. The Rhino moves, and the Marines get out. The Marines and the Rhino both pay their 5 cm penalty for the Marines to disembark. If the disembarking Marines have to spend movement to 'move out' from the Rhino, the Marines are paying a second cost for disembarking.

I don't get it -- what second cost? You pay 5 cm once to disembark, then you measure from the Rhino. The Space Marines must have at least their own base width remaining to disembark into base contact - but if they have more remaining, then they can move further. Where's the double cost?

I'm starting to think that your interpretation may be more consistent overall (while allowing 'unearned base width' of movement, which my interpretation avoids). But I don't see how it is any more obvious in the actual rules text.

---

All that said, your proposal sounds good to me and seems to even out the various oddities and base-width problems. It sounds like something I'd rather play with than either of our direct interpretations from the rules as written. So, I think it would be good as a topic in the Experimental section. What say you?

**Comment by IJW-Wartrader** [comment]
> That quote isn't really evidence for a particular interpretation in my view. It is so vague that your interpretation really depends on what presumptions you're already making.

For what it's worth, I'm trying to apply Occam's Razor and not add extra variables. So:

- The majority of Infantry have Speed 10 cm and the quote doesn't say that it's an exception for faster units, so I assume that it applies to any unit that has 10 cm of movement available.
- The rules usually talk about single moves, and the quote doesn't say that it's an exception ('you can do this while marching' or 'you can do this across two phases' or similar), so I assume that it's possible in a single move.

---

> > A unit of Marines starts the Movement phase in a Rhino. The Rhino moves, and the Marines get out. The Marines and the Rhino both pay their 5 cm penalty for the Marines to disembark. If the disembarking Marines have to spend movement to 'move out' from the Rhino, the Marines are paying a second cost for disembarking.
> 
> I don't get it -- what second cost? You pay 5 cm once to disembark, then you measure from the Rhino. The Space Marines must have at least their own base width remaining to disembark into base contact - but if they have more remaining, then they can move further. Where's the double cost?

A Space Marine is in a Rhino. How much movement does it cost them to go from being inside the Rhino to being outside the Rhino (aka 'disembark')? If you have to measure from the Rhino, 'the total cost in movement to get out of the Rhino' is _greater than 5 cm_. That's the double cost.

---

But let's look at the original text again:

> Units that can transport are able to carry other units across the battlefield. It costs a Transport unit 5cm of its movement to pick up or set down a passenger unit or cargo.

> Units being carried must also pay 5cm of their movement to be picked up and/or set down.

The original Transport text uses 'pick up' and 'set down'. To me, those terms don't infer anything about requiring further movement. Paraphrasing slightly, 'Units being carried pay 5cm of their movement to be set down.'.

You pay your 5 cm of movement, you get set down, you're out of the vehicle.

---

And a third angle - from the purely practical side, it's really fiddly to measure moving out of the Transport, and 3rd edition goes out of its way to avoid that level of fiddliness.

> The Space Marines must have at least their own base width remaining to disembark into base contact

If the Space Marine unit ends in base contact, most of its base ends up _more_ than base width from the vehicle, so you would need more than just the base width remaining.

<img width="342" alt="disembarking" src="https://user-images.githubusercontent.com/17686203/122666449-283fa200-d1a5-11eb-9544-f7430066c093.png">

Obviously this is adding a layer of abstraction by putting the Rhino on a base, but a 40 mm strip base is substantially larger than a Rhino, so even if the base ends up touching the long edge of an unbased Rhino this still applies.

---

A fourth issue (and yes, this one is absurd, but that's the point... 😉).

Pick up/set down or embark/disembark are antonyms, so they should be mirrored manoeuvres unless the rules tell us to treat them differently from each other. The process of embarking is the exact reverse of disembarking.

Therefore, if the Space Marine unit has to measure to get all the way _out_ of the Rhino, it also has to measure to get all the way _into_ the Rhino. 😜

---

> All that said, your proposal sounds good to me and seems to even out the various oddities and base-width problems. It sounds like something I'd rather play with than either of our direct interpretations from the rules as written. So, I think it would be good as a topic in the Experimental section. What say you?

I'll put up a poll later, let's see what feedback we get. If any.

**Comment by digi-brain** [comment]
Hmmm. I could still quibble the detail in some of your points, but think it'd be academic at this point -- I'm mostly persuaded by your interpretation as more likely to be true to the design intent. I still don't like it any better though, so I'll definitely be looking to your alternative proposal as a 'better way to play' in my next game.

Outside of the main body of the rules where we seek general acceptance, I think that it's our prerogative if we want to include alternative ways to play or other experiments/suggestions/notes/whatever. But yes, it is good to see what people think and see what other ideas and variations and edge cases they put forward, and to use this feedback to refine our ideas.

**Comment by digi-brain** [comment]
Though of course, if the proposal gets strong support then maybe we should put it into the main rules...

**Comment by IJW-Wartrader** [comment]
> Outside of the main body of the rules where we seek general acceptance, I think that it's our prerogative if we want to include alternative ways to play or other experiments/suggestions/notes/whatever. But yes, it is good to see what people think and see what other ideas and variations and edge cases they put forward, and to use this feedback to refine our ideas.

Yeah. For clarity, I definitely don't see the polls as driving our direction (because that would likely end up a fustercluck), but if we've come up something like 'place completely within 5 cm' then it's handy to get a feel for whether the community has extreme feelings one way or the other, or spots rules and balance issues that we haven't. Within the limits of pretty low engagement in a lot of these polls and discussions...

> Though of course, if the proposal gets strong support then maybe we should put it into the main rules...

That's the aim.

**Comment by digi-brain** [comment]
Yeah, I guess I was thinking that we'd put it in the experimental/whatever section first, and we don't need consensus for that. A move to the main rules could come later, subject to testing and consensus. Whereas I think you've gone for the more direct approach of "let's check consensus now, and put it straight into the main rules now if it seems okay"?

I'm okay with the latter in this case; it seems like it should work okay and the rules as written are unsatisfactory whichever way you interpret them, and awkward to rewrite. So, given the problems, 'replace' seems better than 'reword'.

**Comment by IJW-Wartrader** [comment]
> Yeah, I guess I was thinking that we'd put it in the experimental/whatever section first, and we don't need consensus for that. A move to the main rules could come later, subject to testing and consensus. Whereas I think you've gone for the more direct approach of "let's check consensus now, and put it straight into the main rules now if it seems okay"?

Yes.

> and the rules as written are unsatisfactory whichever way you interpret them, and awkward to rewrite

This was my baseline. What we currently have in the Transportation page is already contentious and will be seen as a rules change by some players*, so we don't 'lose' anything by replacing it with something else.

*Please note that I'm not trying to infer anything about either of us being right or wrong on this one, just echoing you that the original rules were messy and unclear.

**Comment by digi-brain** [comment]
>*Please note that I'm not trying to infer anything about either of us being right or wrong on this one, just echoing you that the original rules were messy and unclear.

No worries, I got that, but thanks. Although having discussed it, and as mentioned above, I do think that your interpretation is likely closer to the original design intent than mine. The original design intent (and wording of such, and potential to see what we've done already as a 'change') is indeed a mess. :D

**Comment by IJW-Wartrader** [comment]
For the next Transportation branch, we need to add the 'completely within 5 cm' rule to embarking, and to surviving destroyed Transports.

Also, the Hitch (X) section on the Transportation page needs a bit of work - it's not written as a list of exceptions or additions to Transport (X), but it needs to have the same clauses about embarking and disembarking within 5 cm. Arguably, it also needs the text about surviving a destroyed Transport, for when a Dangerous terrain test destroys the Hitch vehicle while it's carrying units.

How would you like the rework to go? Move all the 'completely within 5 cm' bits and destroyed vehicles into a general 'Transportation unit' section, and then the Transport (X) and Hitch (X) sections add their specific clauses? So Transport (X) and Hitch (X) would mention their different 'costs', and Hitch (X) adds the _requirement_ that the transported units disembark again in the same phase.

**Comment by digi-brain** [comment]
Sounds sensible to me.

>How would you like the rework to go? Move all the 'completely within 5 cm' bits and destroyed vehicles into a general 'Transportation unit' section, and then the Transport (X) and Hitch (X) sections add their specific clauses? So Transport (X) and Hitch (X) would mention their different 'costs', and Hitch (X) adds the requirement that the transported units disembark again in the same phase.

I'm not sure exactly, sometimes you have to experiment with it a bit and see how it shakes out. But in principle yes, I agree that it will probably be most effective to have the 'shared' or 'general' elements in the main Transportation topic, and the 'exceptional' or 'specific' bits in the Transport (X) and Hitch (X) topics. We were sort of thinking along those lines already, we've just accumulated some more bits to feed into it.

**Comment by IJW-Wartrader** [comment]
OK, I'll see if I can do a first pass later this week.

**Comment by IJW-Wartrader** [comment]
First pass done, transportation is the only page that has been altered.

**Comment by digi-brain** [comment]
Cool, go ahead and make a pull request?

It's too effing hot to think straight in my house at the moment, but the weather is due to break soon... :-D

**Comment by IJW-Wartrader** [comment]
Pull request started, after some more minor tweaks.
