### ISSUE TITLE
Menu test branch

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#12]
As far as I'm concerned, we've currently 'fixed' the outstanding issues and have a system that works, especially once we've implemented your suggestion of putting all the abilities back into one list and tagging them by type.

_Originally posted by @IJW-Wartrader in https://github.com/GameBrains/er-core/issues/10#issuecomment-860752151_

**Comment by IJW-Wartrader** [comment]
While thinking about navigation and the special abilities section, I thought of an alternative to listing the whole lot alphabetically, but without hiding them all by nesting them within the four ability types.

Put the types and the abilities at the same level, and use Antora's/Asciidoc's standard formatting to pick out the types.

The current commit uses bold italic for some, and bold highlighted for others, so that they can be compared.

<img width="390" alt="Screen Shot 2021-06-14 at 16 42 36" src="https://user-images.githubusercontent.com/17686203/121920072-93195500-cd2f-11eb-8084-43f48b69e3e4.png">

What do you think about this as an alternative? I'm slightly hesitant about an alphabetical list because that lumps the Data sheet modifiers in with all the other abilities, and once you're playing a game you don't care about them.

Hmm. Maybe even keep the Data sheet modifiers within a nested sub-level.

**Comment by IJW-Wartrader** [comment]
P.S. Just for curiosity, I added Jump Packs links in two places and it didn't cause anything to crash when building the site. When you go to the Jump Packs page, both navigation menu items are in bold, but the breadcrumb navigation at the top of the page says that it's a Data sheet modifier, as expected as that's where it appears first.

**Comment by IJW-Wartrader** [comment]
Although the formatting in the menu navigation is also used in the breadcrumb navigation. Which isn't too surprising when you think about it. This version hasn't been committed yet.

<img width="928" alt="menu-test-double-jump-packs" src="https://user-images.githubusercontent.com/17686203/121947170-a6d3b400-cd4d-11eb-9d5e-06afcaa1411a.png">

**Comment by IJW-Wartrader** [comment]
P.S. There is no pull request for this branch, as it is just for testing purposes.

**Comment by digi-brain** [comment]
I see what you're trying to do, but I'm always wary of visual trickery that isn't backed by something more concrete. One thing here is that it is problematic when a 'parent' topic like 'Unit abilities' is no longer actually a parent.

Further to our video chat, I've done something a bit different, but with the same general goal in mind.

- One flat list of all abilities, alphabetical order. [Minor quibble: Although the file system puts `assault-1.adoc` before `assault.adoc`, I'm not sure that we should do the same for 'Assault +1' and 'Assault'...]
- Note the new topic at the head of the list: This explains the types in one place. I could've put all this back into `special-abilities-adoc`, but I didn't like how long it made that topic and it felt like it made sense as a discrete topic. I think it works fine as the first topic in the list, and I have done similar elsewhere.
-  Note the ability 'labels' in the Jump Packs topic. I played around a bit with CSS, but for a couple of reasons I went with a quick and dirty solution instead — just plain text in the monospace 'code' styling. If we don't like how it appears in search snippets in future then we can cross that bridge when we come to it.

![image](https://user-images.githubusercontent.com/34416576/122571929-28c12700-d045-11eb-8cba-5c85a7665859.png)

What do you think?

**Comment by digi-brain** [comment]
Oh, and what I was saying about giant ToC for a long section on mobile view — ignore that, I was thinking about the in-page ToC, which is different anyway. (And because we use good topic-based writing, the in-page ToC never gets to be giant.)

**Comment by IJW-Wartrader** [comment]
That looks good. In the long run it would be great if we could add the ability types as tags, and when you click on the tag you get a list of all abilities with that tag. But I suspect that doing that in Antora is going to involve manual creation of those lists.

---

Going off on a (big?) tangent, this discussion has helped me work out why the navigation on the Remastered site felt so 'weird' at first. Clicking on items in the navigation menu was unpredictable and never worked quite as expected.

In hindsight, navigation items that I expected to be disclosure buttons turned out to be links to new pages, _instead_ of being disclosure buttons. So I'd click on a line with a disclosure triangle, expecting the 'standard' behaviour where this shows the next level of items in the navigation menu, and suddenly I'd be on a new page and the navigation menu had closed the sub-section I was previously looking at, instead of showing me both sub-sections at once!

Without having consciously worked this out, this is why my original version of the Special Abilities menu had non-linked headers for each type of ability, and kept the descriptions of the abilities in another page - each type of ability in the section now worked as expected, and you could open and close each type-section independently without ending up on a new page unexpectedly.

Looking at it all more carefully in a desktop browser, docs.antora.org and (less consistently) docs.asciidoc.org have the top-level sections as non-linking items so that they work as disclosure buttons, and the lower level ones that are links have a :hover underline behaviour to show that they are links, and the small disclosure triangle still works as a disclosure triangle. 

**Summary** - I don't think there are any easy fixes. But we need to bear in mind that the default Antora navigation, if _all_ menu items are links, is not easy to use on mobile devices where there is no :hover behaviour, and where the disclosure triangle icons are too small to work as touchable parts of the interface. 

It _might_ be worth making the top-level menu items ('Main rules' 'The Movement phase', etc.) into non-linking items, but obviously that would be more complex than simply changing the nav.adoc files as it would require restructuring the actual sections and pages. :-(

**Comment by digi-brain** [comment]
>That looks good. In the long run it would be great if we could add the ability types as tags, and when you click on the tag you get a list of all abilities with that tag. But I suspect that doing that in Antora is going to involve manual creation of those lists.

Yes, there's nothing built in to handle that type of behaviour as far as I know, so it would require some kind of custom coding -- or possibly there is an extension already that could do it. (I stumbled across some at one point, but only took a brief look and didn't work out how to use them.)

It'd be nice to have as contributors, but I don't think players would use the feature much though would they? I'm struggling to think of when a player would especially want to see only a list of 'detachment abilities' for example, as opposed to just looking up a specific ability in the alphabetical list. Do you have use cases in mind?

---

>Going off on a (big?) tangent...

Interesting. I never encountered anything that I thought was atypical or unexpected here. It did exactly what I expected.

I generally avoid having menu items that you click but that don't link to an actual topic. From experience, it nearly always results in an uneven experience because at some point you want to cross-reference to it as the section parent. So I write and structure in such a way that there is always a proper section parent topic, that is, an actual page rather than just a navigation item. Also, depending on the system and context, the empty navigation header doesn't always play nicely when it comes to a print version...

>expecting the 'standard' behaviour where this shows the next level of items in the navigation menu

In my experience, that isn't standard at all, unless we're talking at cross-purposes. I only expect that when I click on the little triangle. That is harder on mobile, but we can probably fix that with CSS in due course.

>Looking at it all more carefully in a desktop browser, docs.antora.org and (less consistently) docs.asciidoc.org have the top-level sections as non-linking items so that they work as disclosure buttons, and the lower level ones that are links have a :hover underline behaviour to show that they are links, and the small disclosure triangle still works as a disclosure triangle.

Yeah, I don't like such inconsistencies. Hence my remarks above about uneven experience and structuring with a proper topic instead.

>Summary - I don't think there are any easy fixes. But we need to bear in mind that the default Antora navigation, if all menu items are links, is not easy to use on mobile devices where there is no :hover behaviour, and where the disclosure triangle icons are too small to work as touchable parts of the interface.
>
>It might be worth making the top-level menu items ('Main rules' 'The Movement phase', etc.) into non-linking items, but obviously that would be more complex than simply changing the nav.adoc files as it would require restructuring the actual sections and pages. :-(

As above, I prefer the opposite solution: Make mobile UI easier to use, don't use odd tricks with empty section navigation headers. Plus, while disclosure of a section without actually browsing to the section (and closing the existing section) is occasionally nice, I've personally never found it to be a critical feature.

**Comment by digi-brain** [comment]
Meantime, if you don't have any objection to the current implementation on this branch, I'd be happy to go ahead and merge it into master -- I think we agree that it is at least more user-friendly than the current four sections?

**Comment by digi-brain** [comment]
I've now added the 'tags' to every ability topic in the branch. So, ready to merge I think.

**Comment by IJW-Wartrader** [comment]
> Meanwhile, if you don't have any objection to the current implementation on this branch, I'd be happy to go ahead and merge it into master -- I think we agree that it is at least more user-friendly than the current four sections?
> [Well, need to add the rest of the 'tags' first of course.]

Fine by me!

**Comment by digi-brain** [comment]
Done! Now live on the site. Nice.
