### ISSUE TITLE
War engine branch plans

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#15]
Adding some stuff here, before I forget it, and so that you can see it to...

- Reverse gear for all WEs, not just for Battlefortresses and Baneblades. Reversing costs all but 5 cm of the unit's Speed, rather than 'reducing' the unit's Speed to 5 cm, to avoid issues with Distortion Cannon suddenly hitting more easily.
- Criticals and sides - add some text about working out 'near/far' side for critical damage results.
- Whatever we end up deciding for WEs as the target of {barrage} weapons.
- As above, for WE ganging up.
- Streamlined Critical Damage tables for most DC4 WEs.

**Comment by IJW-Wartrader** [comment]
So that it doesn't get lost when the Transportation pull request is closed...

- In games where war engine orders are not in use, how do orders for transported detachments work?

In the discussions on FB, I think the consensus was to limit the transported detachment to normal or Assault orders, which is consistent with Drop Pod arrival.

**Comment by digi-brain** [comment]
Yes, that sounds sensible to me.

**Comment by digi-brain** [comment]
>Reverse gear for all WEs, not just for Battlefortresses and Baneblades. Reversing costs all but 5 cm of the unit's Speed, rather than 'reducing' the unit's Speed to 5 cm, to avoid issues with Distortion Cannon suddenly hitting more easily.

Just to say, independent of this, I added a note on my first pass through that part of the War Engine rules.

I never looked closely before but always thought that the original designer's note amounted to 'you can reverse up to 5 cm'. But, on close inspection, it looks to me like the actual wording amounts to 'it *costs* 5 cm to reverse' (much as any turn after the first costs 5 cm). Very different — but also much too liberal I think, so perhaps a fixed 5 cm would be better in any case...?

Even with fixed 5 cm reverse movement, where a war engine is very fast (with Speed 25 cm or more, mainly Eldar Revenant titans and SH tanks ), the player could get a bit more backward movement if they really want it. By virtue of two pairs of turns (that cost 15 cm total, with the freebie) at either end of the actual move. As long as they don't come unstuck with dangerous terrain part-way through they'd effectively achieve a 10 cm reverse move - which doesn't seem unreasonable for such fast units.

I agree that, given the existing abstraction for Distortion Cannon that decouples a war engine's actual movement from its Speed value, it'd be better not to tie reverse movement to a temporarily reduced Speed value. For both consistency and simplicity.

**Comment by IJW-Wartrader** [comment]
> I never looked closely before but always thought that the original designer's note amounted to 'you can reverse up to 5 cm'. But, on close inspection, it looks to me like the actual wording amounts to 'it _costs_ 5 cm to reverse' (much as any turn after the first costs 5 cm). Very different — but also much too liberal I think, so perhaps a fixed 5 cm would be better in any case...?

Yes, for the Battlefortresses, Shadowswords, and Baneblades. I'd prefer a maximum move of 5 cm for all war engines.

**Comment by digi-brain** [comment]
Yes, seems like a good idea to codify a reverse move of up to 5 cm for **all** war engines.

Also, just to note that I got a paragraph above wrong (because each turn is actually 45 degrees, not 90 degrees as I had in my head at the time), so I retract it:

>Even with fixed 5 cm reverse movement, where a war engine is very fast (with Speed 25 cm or more, mainly Eldar Revenant titans and SH tanks ), the player could get a bit more backward movement if they really want it. By virtue of two pairs of turns (that cost 15 cm total, with the freebie) at either end of the actual move. As long as they don't come unstuck with dangerous terrain part-way through they'd effectively achieve a 10 cm reverse move - which doesn't seem unreasonable for such fast units.

**Comment by digi-brain** [comment]
And with respect to streamlined critical damage tables... 

My friend and I played a game at the weekend with only war engines and a few aircraft (Eldar and Imperials each had one battle titan, two scout titans and four super-heavy tanks).

I think it is fair to say that just about all of the war engine damage tables need some attention — they are all over the place. And, as much as I like the character that tables add in principle, in practice it's a real pain to keep track — to the extent that I feel that while your 'dry wipe' data sheets will of course help, perhaps we should consider whether to go much further to reduce the insanity? I suppose this would be contentious with the community. Perhaps another option would be to rationalise a bit, and then offer a 'speed play' variant for use when you have more than a couple of war engines on the board.

I mean, as it stand it is easy enough when a war engine is permanently immobilised — you just mark it with an order die. But when you also have results or combinations of results that yield:

- some that are immobilised for the rest of the turn
- some that are immobilised until repaired
- some that are immobilised and unable to shoot for the rest of the turn
- some that are immobilised and unable to shoot until repaired
- some that are not immobilised, but are unable to shoot for the rest of the turn or until repaired
- or endless other combinations of stuff that you can't track 'on the tabletop' and can't easily recall at a glance...

...then it seems a bit insane. We had several such variations in effect at once, and we found it rather frustrating. I can see why in EA they went for a simple roll at the end of each turn to see what happens with a critical. I officially retract my support for 'interesting and characterful' damage tables!

**Comment by IJW-Wartrader** [comment]
> I suppose this would be contentious with the community.

That's my worry. What I've been doing is using the same simplified table for all DC4 war engines on the grounds that they're the ones that you're likely to have multiples of. So your game would only have had the more complex chart for the two Battle Titans.

My current DC4 chart uses a d6, and is roughly:

1. Weapons can't be used for the rest of the turn.
2. Immobilised for the rest of this turn.
3. Both of the above.
4. Weapons can't be used until repaired (treating them all as a single damaged item).
5. Immobilised until repaired.
6. Catastrophic Damage.

**Comment by IJW-Wartrader** [comment]
> ...then it seems a bit insane. We had several such variations in effect at once, and we found it rather frustrating. I can see why in EA they went for a simple roll at the end of each turn to see what happens with a critical. I officially retract my support for 'interesting and characterful' damage tables!

?

Criticals are different for every war engine in EA, and some have semi-random effects with a d6 being rolled to see what happens.

**Comment by IJW-Wartrader** [comment]
### Shooting at war engines > mixed immobilisation

> {blank}[TODO: Cross-reference the Firepower table, once we've added it. Also, we actually target detachments not units, and we need to clarify what happens when a War Engine detachment has a mix of Immobilised and non-Immobilised WE units.]

I would expect this to be treated the same as a target detachment that's partially in cover. The attacker has to choose between:
One die per Firepower, but hits can only be allocated to IMM war engines.
Column 1, and hits can be allocated to any war engine.

### Hit allocation
I'll have to dig out the discussions, but from memory this was overwhelmingly in favour of changing it to EA-style 'allocate hits to the closest up to current DC, then allocate to the next closest etc.'. We can probably borrow phrasing from Robust for this.

**Comment by IJW-Wartrader** [comment]
I found the previous discussion, my last suggestion appears to have been to allocate current DC + current shields/fields.

https://www.facebook.com/groups/1952676958177757/posts/3625167407595362/

**Comment by digi-brain** [comment]
>?
>Criticals are different for every war engine in EA, and some have semi-random effects with a d6 being rolled to see what happens.

It's a while since I played EA, so my memory is hazy: But my point is that in EA it's something that is very simple resolve and when there is anything to track it is very straightforward. Not a laundry list of variations and combinations that you have to track for the rest of the turn, and/or until repaired, and/or for the rest of the game.

"Oh hang on, was that unit not allowed to move or shoot until the end of the turn, or was it that one? Or was it allowed to move but not shoot until repaired? No that was that one... but that one there can't move ever again, and can't shoot for the rest of this turn"... too much.

**Comment by digi-brain** [comment]
> ### Shooting at war engines > mixed immobilisation
> > {blank}[TODO: Cross-reference the Firepower table, once we've added it. Also, we actually target detachments not units, and we need to clarify what happens when a War Engine detachment has a mix of Immobilised and non-Immobilised WE units.]
> 
> I would expect this to be treated the same as a target detachment that's partially in cover. The attacker has to choose between: One die per Firepower, but hits can only be allocated to IMM war engines. Column 1, and hits can be allocated to any war engine.

Yes, that seems reasonable. I hadn't given it much thought before, I just made the note and moved on — but this follows the existing logic nicely. We should make this explicit I think.

> ### Hit allocation
> I'll have to dig out the discussions, but from memory this was overwhelmingly in favour of changing it to EA-style 'allocate hits to the closest up to initial DC, then allocate to the next closest etc.'. We can probably borrow phrasing from _Robust_ for this, but we also need to decide if it should be **initial DC** like EA, or **current DC** like _Robust_.
> 
> EDIT - follow-up, should this include Power Fields/Void Shields?

Hmm... you could argue this all different ways, and I'm not sure if there are any especially strong pros and cons in each case. Seems like the original allocation regardless of DC and shields is the simplest. Is there any really good reason to change that? (Apologies if this has been discussed at length and I've forgotten.)

If yes, then perhaps 'initial DC, regardless of shields' is the next simplest. Options that force us to check the current amount of damage and number of shields seem rather unappealing to me and not in keeping with the streamlined approach of third edition.

**Comment by digi-brain** [comment]
Oh, I need to get around to reading the link you posted to a discussion — that might answer at least part of my question.

**Comment by digi-brain** [comment]
> > I suppose this would be contentious with the community.
> 
> That's my worry.

Yes, that's a valid concern. It's one of those things that you can't really appreciate until you actually play a game with a decent number of war engines. When I was just theorising, I was wary of stripping back the damage charts too much for fear of losing 'character' — but after the practical experience, I feel quite differently. Maybe it is a conversation to have at some point. Or perhaps I should just knock up a 'speed play' variant on the damage tables at some point, and stick it in the experimental section.

> What I've been doing is using the same simplified table for all DC4 war engines on the grounds that they're the ones that you're likely to have multiples of. So your game would only have had the more complex chart for the two Battle Titans.
> 
> My current DC4 chart uses a d6, and is roughly:
> 
> 1. Weapons can't be used for the rest of the turn.
> 2. Immobilised for the rest of this turn.
> 3. Both of the above.
> 4. Weapons can't be used until repaired (treating them all as a single damaged item).
> 5. Immobilised until repaired.
> 6. Catastrophic Damage.

That's 'less worse', but could still mean more than I'd like to track at any given moment. I'm not blessed with a great memory for this kind of thing.

Back to my 'speed play' idea: Ideally, critical damage effects should

- resolve immediately so we have nothing to track (destroyed) or so that we track something we're already tracking (lose DC, gain a Blast marker)
and/or
- require that we track the existence of ongoing critical damage effects with a **single** marker type (though multiples thereof if necessary) that we can put next to the unit, and we resolve effects with a die roll in the Rally phase (simple instant-resolution effects, similar to EA).

**Comment by IJW-Wartrader** [comment]
Yes, a speed play option could be good in the experimental section.

> That's 'less worse', but could still mean more than I'd like to track at any given moment. I'm not blessed with a great memory for this kind of thing.

Mine isn't either, which is one of the purposes of the card-sized datasheets - when there are crits in effect you flip the card for that war engine and mark the crit. As soon as it's cleared, you can wipe off the dry wipe marker and flip the card back over again.

**Comment by digi-brain** [comment]
>Mine isn't either, which is one of the purposes of the card-sized datasheets - when there are crits in effect you flip the card for that war engine and mark the crit. As soon as it's cleared, you can wipe off the dry wipe marker and flip the card back over again.

Definitely a big improvement, I'd like to have some of your cards to hand next time for sure.

**Comment by IJW-Wartrader** [comment]
Adding some notes here as I go through the various files...

### War engines and blast markers
Corrected it from 'more than 15' to '15 or more'.
I've also rewritten the text to work better for detachments, as the original GW text was written from the point of view of solo WEs with 15+ DC.
Added a couple of examples for solo WEs and detachments, so a Great Gargant (DC18) always gets +1, but a detachment of four Baneblades (DC4 each) that's lost a Baneblade (new total initial DC 12) no longer gets +1. This is an assumption on my part, as I don't think it makes sense for one remaining Baneblade to get +1 because it used to have three others!

### Shooting at war engines > mixed mobility
I've added a first pass text adapted from the text for shooting into the open.

### War engine critical damage
I've removed all references to 'location' due to multiple critical results that don't affect a specific location.

### Main rules > Attempt repair
And the same here.

### War engine catastrophic damage

> TODO: Ideally, we should change some terminology to disambiguate the general usage of the term 'destroyed' from the specific result of 'Destroyed' (rather than 'Wrecked') on catastrophic damage tables.

I suggest 'Wrecked'/'Killed' and 'Annihilated'. More organic WEs like Biotitans use 'Killed' instead of 'Wrecked'.
It would be nice to find a term that covers both Wrecked and Killed, but I can't think of one at the moment.

### War engine shields
All use of 'recover/recoverable' changed to 'repair/repairable' for consistency with the repair rules.

### War engines in close combat
I've changed the 'ganging up' limit to a 'base contact' limit, as per the current 'Split speed redux and general movement' pull request.
I've also made a rules change as discussed on FB, so that you're limited to the target's _full_ initial DC rather than halving it, and added a NOTE.e40k.

> TODO: How do War Engine units -- or a mix of War Engine and regular units -- gang up on on other War Engine units?

I'll have to dig out the discussion again, but the consensus was that all the attackers count as single units for this. Otherwise it's almost impossible for multiple WEs to gang up on a single similar-size WE.

> TODO: In a detachment of multiple War Engine units, can units that are not in base contact with the enemy provide supporting fire like regular units can? If so, is it just +1 to the Assault value total, or should it be '+half the current Damage Capacity' as it is when they support other detachments?

Consensus was to allow the ones not in base contact to support with half current DC, and that this doesn't 'use up' their chance to support other detachments.

> Note that you may allocate hits only among units that the War Engine is actually in base contact with. So, even if you score excess hits, your War Engine unit can’t destroy more units in close combat than it is actually in base contact with.

This appears to have been written (in the GW original) on the basis that it was always a solo WE with nothing else in the combat. I suggest that we change this to use the same wording as normal combats, so that your pool of hits can be allocated to anyone in base contact anywhere in the combat.

**Comment by IJW-Wartrader** [comment]
> Back to my 'speed play' idea: Ideally, critical damage effects should
> 
> * resolve immediately so we have nothing to track (destroyed) or so that we track something we're already tracking (lose DC, gain a Blast marker)
>   and/or
> * require that we track the existence of ongoing critical damage effects with a **single** marker type (though multiples thereof if necessary) that we can put next to the unit, and we resolve effects with a die roll in the Rally phase (simple instant-resolution effects, similar to EA).

By the way, a really quick-and-dirty system which I'm planning to use when I finally field Angron plus a full set of eight over-sized Bloodthirsters is to treat them as DC3 or 4 WEs, and the critical effect is to lose an extra DC. Or possibly d3 DC. Angron will then get a 'normal' critical chart, unlike his bodyguards.

**Comment by digi-brain** [comment]
Interesting. The D3 bit got me thinking a bit more on my speed play idea. What do you think of this as a possibility:

- For *all* DC3/DC4 units: D3 damage **instead** of the normal 1 damage from the hit.  No other effects to track.
- For DC>4 units: As above, but also mark the unit to show that there is an ongoing critical effect. Then, at the Repair step in the Rally phase, roll to see what happens against a very simple set of outcomes that don't require fiddly tracking, similar to EA.

This should simplify matters **a lot**.

Could perhaps add an additional Blast marker for each critical too. I'm not 100% on this — but my thinking is that given the suppression and Leadership tests they force, it'd go some way to replace the various "can't move/can't shoot" results of the original.

I've just realised that I haven't factored in 'Immobilised' here in any form. Should add that in somehow.
Perhaps the defending player should take a Leadership test immediately after a critical hit; if they fail then the WE is immobilised until they pass a Leadership test in the next Movement phase. [Just one idea that sprang to mind — it would be quite a change from the usual processes, and so I wouldn't be surprised if it gives rise to some undesirable outcomes that haven't occurred to me yet.]

**Comment by IJW-Wartrader** [comment]
d3 damage instead sounds like a great idea.

It's just occurred to me that the simplified d6 chart is _almost_ identical to the results on the 40k vehicle damage dice from 3rd to 5th edition, which are cheap to pick up. I just need to change result 2 to 'can't use weapons' and it's an exact fit!

**Comment by IJW-Wartrader** [comment]
> ### Shooting at war engines > mixed mobility
> I've added a first pass text adapted from the text for shooting into the open.

Additional:

### Shooting at war engines > Allocation of hits in War Engine detachments
I've tweaked this by copying text from S6 Hit allocation to reinforce that it uses the standard front-to-back hit allocation, one hit at a time. Current/initial DC doesn't matter for this.

We might want to add an experimental page for those players who want to use more 'sane' hit allocation methods that kill off the closest WEs instead of leaving a bunch of them half-dead... 🤣😭

>> Note that you may allocate hits only among units that the War Engine is actually in base contact with. So, even if you score excess hits, your War Engine unit can’t destroy more units in close combat than it is actually in base contact with.

> This appears to have been written (in the GW original) on the basis that it was always a solo WE with nothing else in the combat. I suggest that we change this to use the same wording as normal combats, so that your pool of hits can be allocated to anyone in base contact anywhere in the combat.

Additional:

### War engines in close combat > Close combat attacks with a War Engine

> Note that you may allocate hits only among units that the War Engine is actually in base contact with. So, even if you score excess hits, your War Engine unit can’t destroy more units in close combat than it is actually in base contact with.

I've changed this to use the usual CC hit allocation (any enemy that are in base contact with your units, not just in base contact with that specific War Engine, and added a NOTE.e40k explaining that GW's text assumed that it was always a solo WE with no allies.

### War engines in close combat > War Engine detachments in close combat
New section added, explaining that you can add half current DC for any WEs in the detachment that aren't in base contact, and that they can still support other close combats. Plus the usual NOTE.e40k

**Comment by IJW-Wartrader** [comment]
### Main Rules > CC5. Roll for close combat hits
Tweaked so that the 2:1 limit talks about base contact, and to make it clearer that hits can be allocated to _any_ contacted enemy anywhere in the combat.


### War engines in support of close combats
> [TODO: But presumably, a WE detachment can support multiple close combats if it has multiple WE units and they each support different combats?]

As written it's per-WE unit not per-detachment, so I don't think we need to add any extra text.


### War engines in firefights > line of fire/weapon arc
> Count the Firepower of each weapon system that can draw a line of fire to at least one enemy unit within 15 cm.

I've changed this to use weapon arcs instead of line of fire, as firefights don't require line of fire.


Right, first pass commit made. I think this might be ready for a pull request.

**Comment by digi-brain** [comment]
> Adding some notes here as I go through the various files...
> 
> ### War engines and blast markers
> Corrected it from 'more than 15' to '15 or more'. I've also rewritten the text to work better for detachments, as the original GW text was written from the point of view of solo WEs with 15+ DC. Added a couple of examples for solo WEs and detachments, so a Great Gargant (DC18) always gets +1, but a detachment of four Baneblades (DC4 each) that's lost a Baneblade (new total initial DC 12) no longer gets +1. This is an assumption on my part, as I don't think it makes sense for one remaining Baneblade to get +1 because it used to have three others!

Good catch on the incorrect 'more than 15' — not sure how I slipped that mistake in. The rest sounds good, except are you certain that the bonus should be based on starting DC rather that starting DC? Seems like that'd be more similar to a regular detachment and then the Baneblade example isn't even needed.

> ### War engine catastrophic damage
> > TODO: Ideally, we should change some terminology to disambiguate the general usage of the term 'destroyed' from the specific result of 'Destroyed' (rather than 'Wrecked') on catastrophic damage tables.
> 
> I suggest 'Wrecked/Killed' and 'Annihilated'. More organic WEs like Biotitans use 'Killed' instead of 'Wrecked'. It would be nice to find a term that covers both Wrecked and Killed, but I can't think of one at the moment.

I'm not sure that the Wrecked/Killed duality on the same fundamental meaning really matters — it's the disambiguation of two meanings for destroyed that matters. But yes, Annihilated seems good, or Obliterated.

> ### War engine shields
> All use of 'recover/recoverable' changed to 'repair/repairable' for consistency with the repair rules.

I thought I only used 'recover/recoverable' in the 'fluff' bits where more varied use of language is acceptable, rather than in the actual rules bits? Perhaps not, or perhaps you think that even in the fluff bits it doesn't sit well sometimes to have variation?

**Note**: I noticed in a quick scan that you've changed some instances of `shields` to `void shields`. We'll have to undo that, or find an alternative approach — I deliberately used plain 'shields' as the generic term to cover both void shields and power fields. See `war-engine-shields.adoc`.

> > Note that you may allocate hits only among units that the War Engine is actually in base contact with. So, even if you score excess hits, your War Engine unit can’t destroy more units in close combat than it is actually in base contact with.
> 
> This appears to have been written (in the GW original) on the basis that it was always a solo WE with nothing else in the combat. I suggest that we change this to use the same wording as normal combats, so that your pool of hits can be allocated to anyone in base contact anywhere in the combat.

Yes, that sounds sensible — even if some people already interpret it that way, it could certainly be more explicit, the solo usage does make it ambiguous at best.

**Comment by IJW-Wartrader** [comment]
> Good catch on the incorrect 'more than 15' — not sure how I slipped that mistake in. The rest sounds good, except are you certain that the bonus should be based on starting DC rather that starting DC?

That’s direct from GW. I assume it’s so that big WEs don’t lose their bonus.

> I'm not sure that the Wrecked/Killed duality on the same fundamental meaning really matters — it's the disambiguation of two meanings for destroyed that matters. But yes, Annihilated seems good, or Obliterated.

I mentioned ‘Killed’ for completeness, and because some of the text was very specific to ‘Wrecked’.

> Note: I noticed in a quick scan that you've changed some instances of shields to void shields. We'll have to undo that, or find an alternative approach — I deliberately used plain 'shields' as the generic term to cover both void shields and power fields. See war-engine-shields.adoc.

I’ll have to check when I’m at the computer, but from memory the places I changed it were specifically about void shields, for example anywhere it talks about repairs.

**Comment by IJW-Wartrader** [comment]
> Good catch on the incorrect 'more than 15' — not sure how I slipped that mistake in.

Looking again, that's because the [original GW text](https://thehobby.zone/resources/e40k-compendium/Content/SpecialRules/WarEngines/WarEnginesAndBlastMarkers.htm) says 'over 15' instead of the '15 or more' text used for Leadership tests. 🙄

----

>> Note: I noticed in a quick scan that you've changed some instances of shields to void shields. We'll have to undo that, or find an alternative approach — I deliberately used plain 'shields' as the generic term to cover both void shields and power fields. See war-engine-shields.adoc.

> I’ll have to check when I’m at the computer, but from memory the places I changed it were specifically about void shields, for example anywhere it talks about repairs.

On checking, I do appear to have only changed it in places that are specific to void shields, not to generic fields/shields. But I just spotted a place where I missed one...

----

>> War engine shields
All use of 'recover/recoverable' changed to 'repair/repairable' for consistency with the repair rules.

> I thought I only used 'recover/recoverable' in the 'fluff' bits where more varied use of language is acceptable, rather than in the actual rules bits? Perhaps not, or perhaps you think that even in the fluff bits it doesn't sit well sometimes to have variation?

In war-engine-shields.adoc you used 'recover/recoverable' in both the fluff text and the rules text.

**Comment by digi-brain** [comment]
_Aside: This conversation is getting REALLY hard to track. I think that this is because we're discussing the sort of detail that the 'conversation' feature in the PR is designed to handle much more effectively._

---

> Looking again, that's because the [original GW text](https://thehobby.zone/resources/e40k-compendium/Content/SpecialRules/WarEngines/WarEnginesAndBlastMarkers.htm) says 'over 15' instead of the '15 or more' text used for Leadership tests. 🙄

FFS. At least it means I wasn't going mad. I vote to keep your edit so that we rationalise on '15 or more', rather than stick with the letter of the original — I imagine that's what you have in mind too.

---

>I’ll have to check when I’m at the computer, but from memory the places I changed it were specifically about void shields, for example anywhere it talks about repairs.

Well done — clearly I started on the right track with the idea but didn't follow it through completely.

---

> In war-engine-shields.adoc you used 'recover/recoverable' in both the fluff text and the rules text.

Ah, my bad. I remember thinking about it in one topic, but clearly I didn't have that in mind in another instance either before or after...! XD
 
> EDIT - which is not meant as a criticism, this kind of stuff is why there are two of us looking at the files!

Yes indeed. I didn't take that one as a criticism, but it is all too easy for that to happen — so it does pay for us both to add something to make it clear we're not being critical sometimes!

It's hard work, but I do believe that the exactitude and overall quality of the content is much higher than it would have been with either of us on our own.

**Comment by IJW-Wartrader** [comment]
> _Aside: This conversation is getting REALLY hard to track. I think that this is because we're discussing the sort of detail that the 'conversation' feature in the PR is designed to handle much more effectively._

👍🏼👍🏼

**Comment by digi-brain** [comment]
> We might want to add an experimental page for those players who want to use more 'sane' hit allocation methods that kill off the closest WEs instead of leaving a bunch of them half-dead... 🤣😭

Yes, it wouldn't hurt to offer the alternative method as an experimental option. I'm in two minds about the method though — on the one hand, it is nice to streamline. On the other hand, it seems like it'd weaken WEs quite a lot — four WEs with one or two remaining DC obviously pose more threat than two destroyed WEs and two with three or four remaining DC.

I'd probably prefer to streamline the damage tables as in my 'speed play' experimental idea first — seems like that'd offer the much bigger gain. If the damage effects are much simpler to track, then an excess of part-damaged WEs is much less bothersome anyway even if you do have to track a bit more DC than in your alternate hit allocation method.

**Comment by IJW-Wartrader** [comment]
I think this can be closed.
