### ISSUE TITLE
Clarify differences hits on flyers from Flak versus air-to-air combat

### ISSUE THREAD

**Issue by digi-brain** [GameBrains/er-core#26]
I think my first pass through drafts for the Flyers section includes a major discrepancy with respect to hits on flyers.

My friend and I were confused in a recent game, when we tried to step through the process for an Intercept mission. It seems that I conflated the air-to-air combat hit rules with the Flak hit rules, whereas they actually differ when you look closely at the original texts. That is, it appears that air-to-air hits are 'direct' much as they are between ground units, but surface-to-air (Flak) hits involve an additional roll to see whether the flyer is actually destroyed or merely 'driven off'.

[Hits on flyers](https://epicremastered.com/core/special-rules/hits-on-flyers.html)

Need to fix this.

**Comment by IJW-Wartrader** [comment]
I'm not aware of a difference. 

Flak causes hits, Snap Fire causes hits, and 'dogfights' cause hits. The 'Hits on flyers' page then explains how to resolve a 'hit' on a Flyer, with no mention of it only applying to specific situations.

So during an Intercepting mission, you make you attack rolls with a Flyer against a specific target. If you get any hits, you roll again to see if the target flies off or is dead.

**Comment by digi-brain** [comment]
We might've just double-confused ourselves. In our muddle, and in the midst of GW's bad writing, it seemed like there was a something contradictory in the Intercept procedure that made me question whether I'd conflated some Flak-specific rules into the 'Hits on flyers' topic. I think our brains were a bit addled at that point after wresting with various other oddities and all the odd combinations of critical damage on many of the 14 war engines that were in play! I'll have a close look again when I get time.

If there is no discrepancy here after all and I got it right the first time then that's good of course, though there might still be room for some sort of clarification around whatever it was that threw us off.

**Comment by IJW-Wartrader** [comment]
> We might've just double-confused ourselves.

That's quite possible, but as you say that can be a sign that more work is needed!

**Comment by IJW-Wartrader** [comment]
I think this can be closed.

**Comment by digi-brain** [comment]
Yes, I agree. Whatever confusion we fell into, I can't remember or see where it might've stemmed from now.

**Comment by IJW-Wartrader** [comment]
Shall I close this?
