### ISSUE TITLE
Move 'E40k difference' notes to footnotes

### ISSUE THREAD

**Issue by digi-brain** [GameBrains/er-core#37]
In their current form, the 'E40k difference' notes ('admonitions' in Asciidoc terms) are rather prominent. They add a lot visual noise that can be quite unwelcome — particularly when there are several of them in a topic that is already relatively 'busy'.

We still want to make it easy for readers to spot things we've changed and to find the notes — but they could stand to be a bit more discrete. Especially given that only players with experience of the original are likely to care, and even then they won't be checking the notes repeatedly.

So, subject to some checks for awkward edge cases, I propose to migrate all of the existing e40k difference notes from admonitions to footnotes, throughout the entire project. Something like:

`footnote:[Difference from _Epic 40,000_: Content of the note here.]`

Or perhaps with an attribute/variable placeholder for convenience and consistency, something like:

`footnote:[{e40k-diff}: Content of the note here.]`

**Comment by IJW-Wartrader** [comment]
That sounds good to me, it will definitely make the main rules text easier to read.

Apologies for the lack of replies recently, it's manic here!

**Comment by digi-brain** [comment]
> That sounds good to me, it will definitely make the main rules text easier to read.

Cool. Yes, these notes do tend to distract from the main text at present don't they.

> Apologies for the lack of replies recently, it's manic here!

No worries, there's no rush — I'm just working through it gradually as I find time, picking on the bits I feel like at that moment.
