### ISSUE TITLE
Fix deviations from standard Leadership test in 'R2. Attempt to rally Broken detachments'

### ISSUE THREAD

**Issue by digi-brain** [GameBrains/er-core#39]
Somewhere along the line we got into a muddle about the test to rally a broken detachment. Our current text has this note:

> The rally test works in a similar way to the Leadership test — but it is different because there are no modifiers and no exceptions for a natural 6.

**This appears to be entirely wrong — some sort of mix-up made its way into the interpretation during earlier editing.**

On the contrary, the original rules text explicitly mentions 'Leadership test' and, while the writing has typical room for ambiguity, it **doesn't** actually suggest that the usual Leadership test modifiers and 'natural 6' clause do not apply here. It only mentions that you can't rally a detachment that has more Blast markers than units remaining (and thus the 'natural 6 is always a success' clause is irrelevant in such cases because you don't get to make the test anyway).

## Corrective action

1. Remove the incorrect note.
2. Undo the phrasing which seeks to define 'Rally test' as distinct from Leadership test. Make it clear that the test to rally a Broken detachment is a normal Leadership test — so the usual clauses still apply (+1 modifier for 15+ units; natural 6 always succeeds), as do abilities that interact with the Leadership test, such as _Stubborn_.
3. Check for other references to 'Rally test' and make sure that phrasing is aligned with the new text and correct interpretation.

**Comment by IJW-Wartrader** [comment]
Sounds good to me!
