### ISSUE TITLE
Units and unit types: Fix INF and VEH definitions to incorporate 'mounted infantry' correctly

### ISSUE THREAD

**Issue by digi-brain** [GameBrains/er-core#44]
At present, `units-and-unit-types.adoc` explains 'mounted infantry' under "Infantry (`INF`)". That is logical in the general sense, but misleading in terms of the actual rules because mounted infantry (bikes, attack bikes, all units with the _Cavalry_ ability) actually have the `VEH` unit type.

So, I think we should rework to explain mounted infantry under the "Vehicle (`VEH`)" entry.

**Comment by IJW-Wartrader** [comment]
Sounds good to me.
