### ISSUE TITLE
Add a guide note to the _Infiltrators_ rule

### ISSUE THREAD

**Issue by digi-brain** [GameBrains/er-core#47]
To date, we haven't been able to reconcile the original rules texts with a workable interpretation of what should happen in various circumstances when Infiltrator units are 'scouting' (that is, at a distance of >30cm <=60cm from their HQ unit).

Until such time as we have a breakthrough or dream up and settle on an effective alternative that the community accepts, I think it'd be good to include some sort of guide note in the _Infiltrators_ topic; an aside along these rough lines:

> To date, we haven't been able to interpret the original rules texts in a way that consistently makes sense of the first bullet point above in various situations that can arise during a game.
So, until we (the playing community) come up with a better solution, we (the {project} contributors) recommend that you **ignore** the above text "However, it is still destroyed if it becomes Broken and it is more than 30 cm away from its HQ unit."
Then, _Infiltrator_ units that are within 60 cm of the HQ are always part of the main detachment for **all** purposes, with no exceptions.
[And something about the tactical/gameplay pros and cons of this in practice?]

@IJW-Wartrader It's been in the back of my mind, but the query in the Facebook group today, and your response to that, prompted me to create this issue. Feel free to correct/build upon my suggestion here. Then at some point I'll create a branch to draft this properly.

**Comment by IJW-Wartrader** [comment]
Sorry for the slow reply, I agree and it's on my list of things to do if you don't get there first!

I probably won't have time to do stuff on the site until mid to late August as I'm prepping for Counter Attack and Bring Out Your Lead!

In terms of presentation, how about we edit the main rules text to remove the text about being destroyed, and add a 'change from Epic 40,000' note with the old rule and the explanation that we haven't been able to work out a consistent and simple way to resolve it. That way, players get the playable version of the rule in the main text, and then a bit of explanation of what the old rule said.

**Comment by digi-brain** [comment]
No probs, but good to know. I haven't had a lot of time on the project lately either, just the odd little bit here and there.

Yes, I think that's a good idea, much easier to live with 👍

**Comment by digi-brain** [comment]
@IJW-Wartrader A note of this kind may still be expedient in the short term -- but I've had some further thoughts which might help us towards a proper solution. I'll open a separate ticket to explain and discuss and see if we can work it into a full solution that we can implement.
