### ISSUE TITLE
Split Speed values, Cavalry and Jump Packs

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#6]
I've copied and adapted this from the _Special abilities v2, mostly Flak_ pull request so that it's easier to discuss and to let us close the pull request sooner.

### Cavalry and Jump Packs

To make the Cavalry and Jump Packs abilities easier,  I propose the following change to **other** parts of the rules.

1. In Data sheets and characteristics > Speed, add something like this:

> Where a unit has a split Speed value such as 20/30 cm, you use the first value for all purposes except Assault moves.

2. In the final Assault moves text, add something like this:

> Where a unit has a split Speed value such as 20/30 cm, you may use the second value if this would bring the unit into contact with an enemy. You **cannot** double the Speed value of the unit during an Assault move.

3. Cavalry becomes a pure Data sheet modifier. It would still be listed in the notes section of the full expanded profile, but within brackets (or similar) to show that it's already been applied. The text for Cavalry would be similar to:

> Where your unit has the {cavalry} ability, apply these changes relative to their base unit:
> * The unit has a split Speed value. The first value is double the base unit's Speed value and the second is triple the base unit's Speed value.
> * The unit becomes a Vehicle unit.

4. Jump Packs has a stub page in the Data sheet modifier list, call it Jump Packs (profile modification) or similar, which links to the main Jump Packs page. The stub page is there purely for consistency so that all profile modifiers are listed together.

5. The Jump Packs page in Unit abilities has two sections (very rough draft):

> Where your unit has the {jump-packs} ability, apply this change relative to their base unit:
> * The unit has a split Speed value. The first value is double the base unit's Speed value and the second is triple the base unit's Speed value.
> 
> Where your unit has the {jump-packs} ability, apply these rules during the game:
> * While moving the unit, you can ignore the effects of terrain as long as the unit doesn't end their move in the terrain.
> * During Assault moves, you can move the unit over enemy units that have already been contacted.

_Editing note - I've tried to give the agency to the player in bullet 5, but it's awkward and the terrain and movement page currently gives the agency to the unit anyway._

Alternatively, for points 4 and 5, put the profile modification into Jump Packs (profile modification) and give both pages 'relevant information' links to each other.

**Comment by IJW-Wartrader** [comment]
Note that current Cavalry units that don't have a base unit, like Kroot Hounds, would just have a split Speed value and a unit type of VEH. They wouldn't need to list 'Cavalry' in their notes because all information would already be in the profile and there's nothing that they're being changed from.

**Comment by digi-brain** [comment]
I know you've started to implement these ideas in the new PR, and I'll look at that soon. I'm just reading this first to make sure I understand, and so I'll add thoughts as they occur to me -- though of course you may have already tackled them in your actual commits.

---

> Where a unit has a split Speed value such as 20/30 cm, you use the first value for all purposes except Assault moves.

A split Speed value on the datasheet isn't the only way to do it of course -- and I'm not sure whether or not it is 'cleaner and clearer' than one value with the explanation of the 1.5x (or +50%) modifier in the Cavalry ability rules. But yes, let's do it and see how it looks.

However:

> for all purposes except Assault moves

As written here, this is problematic because it is for all purposes except a **sub-set** of assault moves -- the charge move (whether or not we word it as such). But I suspect you'll have adjusted for this in your actual edits.

---

> The unit becomes a Vehicle unit.

This gives me pause for thought as compared with something like "For the purposes of movement, threat the unit as if it were a Vehicle unit". I see your point that if we can't think of any conditions where they aren't in effect a Vehicle unit as far as the rules are concerned then we might as well call them this. However:

1. I wonder if there might be a situation in future where we do want to differentiate in some aspect other than movement.
2. It just sounds wrong and likely to raise eyebrows -- though we could perhaps reword it a bit to make the abstraction clear.

---
> Jump Packs has a stub page in the Data sheet modifier list, call it Jump Packs (profile modification) or similar, which links to the main Jump Packs page. The stub page is there purely for consistency so that all profile modifiers are listed together.

Yes, that sounds fine. If we think we can improve on this after we've actually seen it then we can.

>Alternatively, for points 4 and 5, put the profile modification into Jump Packs (profile modification) and give both pages 'relevant information' links to each other.

As above, I think that we should go with your first idea and see how it looks, then adjust if we see fit.

---

> Editing note - I've tried to give the agency to the player in bullet 5, but it's awkward and the terrain and movement page currently gives the agency to the unit anyway.

I don't quite understand what you mean here, but I'm sure we'll work through it.

**Comment by IJW-Wartrader** [comment]
> > Where a unit has a split Speed value such as 20/30 cm, you use the first value for all purposes except Assault moves.
> 
> A split Speed value on the datasheet isn't the only way to do it of course -- and I'm not sure whether or not it is 'cleaner and clearer' than one value with the explanation of the 1.5x (or +50%) modifier in the Cavalry ability rules. But yes, let's do it and see how it looks.

We then run into problems with units like Kroot Hounds again. The beauty of a split Speed value from a game design point of view is that you can just use the split value without being forced into applying an ability. If we want to do this without a change to the Speed characteristic, we'll probably have to add another unit ability and split 'Cavalry' even further.

---

> > for all purposes except Assault moves
> 
> As written here, this is problematic because it is for all purposes except a **sub-set** of assault moves -- the charge move (whether or not we word it as such). But I suspect you'll have adjusted for this in your actual edits.

Good point. It would need to be 'for all purposes except charging into base contact' or similar.

---

> > The unit becomes a Vehicle unit.
> 
> This gives me pause for thought as compared with something like "For the purposes of movement, threat the unit as if it were a Vehicle unit". I see your point that if we can't think of any conditions where they aren't in effect a Vehicle unit as far as the rules are concerned then we might as well call them this. However:
> 
> 1. I wonder if there might be a situation in future where we do want to differentiate in some aspect other than movement.
> 2. It just sounds wrong and likely to raise eyebrows -- though we could perhaps reword it a bit to make the abstraction clear.

But they **do** become a Vehicle unit. Although in the Cavalry file I used 'The base unit's unit type changes from Infantry to Vehicle.'. We've been through this in detail, Rough Riders and similar units **are Vehicles**. I don't see another consistent way to read the original rules, or to write a new rule.

It's not just a case of not being able to think of conditions where they wouldn't be a Vehicle, we know it applies to movement and we know it applies to shooting, and 'Cavalry [units] are counted as vehicles' is extremely unambiguous for the standards of Epic 40,000 rules texts.

---

I've not added the Jump Packs (modifier) page, and am about to head to Chris's for a game (yay!), so will do it tomorrow if you don't get there first!

**Comment by digi-brain** [comment]
> We then run into problems with units like Kroot Hounds again. The beauty of a split Speed value from a game design point of view is that you can just use the split value without being forced into applying an ability. If we want to do this without a change to the Speed characteristic, we'll probably have to add another unit ability and split 'Cavalry' even further.

Well, I'm agreeing with you that we should try the split approach and see how it looks.

However, in consideration of a possible alternative, my first idea on that doesn't mean "do this without a change to the Speed characteristic", which would indeed be awkward with Kroot hounds and such. Rather, it means don't include the second value that you're adding on the data sheet -- leave the 'add 50% for a charge move' part to the Cavalry ability. The units would continue to have the Cavalry ability, as at present, but the datasheets would show the primary **modified** value (or baseline value for units that don't have a base unit anyway, like Kroot hounds). Of course we change the way we explain the Cavalry ability to make all this clear, which we have to do anyway

I've only roughed this out in my head, but I feel like this approach might be less of an adjustment for players, and neater in the execution -- though perhaps there is some aspect of the different use cases or your detachment builder that I've not considered.

---

> But they **do** become a Vehicle unit.

Okay, from memory I thought it was essentially just a movement thing (must've been thinking of Epic Armageddon, where this is true for _Mounted_). So I looked it up to check what you mean:

> _Because you can't ride a horse through a building very easily, take cover properly and so on Cavalry [units] are counted as vehicles._

Okay, I see what you mean, although to be precise they don't **become** a Vehicle unit -- we **count them as** a Vehicle unit. That's the sort of thing I was alluding to when I said "we could perhaps reword it a bit to make the abstraction clear". It's just weird to say that they are actually **are** vehicles -- but okay to say 'treat them in all respects as if they are vehicles' when that's how the rules work, as in this case.

---

Hope you're both having a great game!

**Comment by IJW-Wartrader** [comment]
> However, in consideration of a possible alternative, my first idea on that doesn't mean "do this without a change to the Speed characteristic", which would indeed be awkward with Kroot hounds and such. Rather, it means don't include the second value that you're adding on the data sheet -- leave the 'add 50% for a charge move' part to the Cavalry ability. The units would continue to have the Cavalry ability, as at present, but the datasheets would show the primary **modified** value (or baseline value for units that don't have a base unit anyway, like Kroot hounds). Of course we change the way we explain the Cavalry ability to make all this clear, which we have to do anyway

I think we're talking at cross-purposes. As far as I can see, any solution that doesn't list two values in the Speed characteristic (or '20 cm x1.5' etc.) causes exactly the same problem we've had with Jump Packs, where it becomes both a Data sheet modifier and a Unit ability. Which is exactly what I've consciously chosen to avoid by using split Speed values.

Without an indication in the Speed characteristic, Cavalry has to contain an in-game rule saying that the unit charges at x1.5 rate, but it's also a Data sheet modifier because it changed the base Speed and unit type. And the Data sheet modifier section would need an exception explaining what happens if there is no base unit to modify.

> I've only roughed this out in my head, but I feel like this approach might be less of an adjustment for players, and neater in the execution -- though perhaps there is some aspect of the different use cases or your detachment builder that I've not considered.

For what it's worth, any unit that moves at a different rate than expected for its unit type **will** have that indicated in the Speed column in the detachment builder. How it's formatted can be discussed, but that it's indicated isn't negotiable.

---

> Okay, I see what you mean, although to be precise they don't **become** a Vehicle unit -- we **count them as** a Vehicle unit. That's the sort of thing I was alluding to when I said "we could perhaps reword it a bit to make the abstraction clear". It's just weird to say that they are actually **are** vehicles -- but okay to say 'treat them in all respects as if they are vehicles' when that's how the rules work, as in this case.

From repeated experience in other games, the 'treat X in all respects as if they are Y' approach needs to be avoided **if at all possible**. It almost universally results in players asking 'But if it counts as Y in all respects, why is it listed as X in the profile? That must mean that there is **some** part of the game where it still counts as X, what rule have I missed that requires them to be listed as X?'.

It adds ambiguity to the rules for no gameplay gain, and no appreciable background gain. Just list their unit type as VEH and be done with it.

---

> Hope you're both having a great game!

We only managed two turns, but it was still a fun game! I'll do a batrep at some point soon.

**Comment by digi-brain** [comment]
> Without an indication in the Speed characteristic, Cavalry has to contain an in-game rule saying that the unit charges at x1.5 rate

In isolation, I don't see a problem with that - it is usual. But you're building up your point.

> it's also a Data sheet modifier because it changed the base Speed and unit type

So, you're saying that it doesn't fall neatly into either data sheet modifier or unit ability, but rather it is a bit of both? Okay, I can see that. But I don't think that that alone must necessarily rule out an alternate approach; it just needs the right explanation and presentation around it.

> And the Data sheet modifier section would need an exception explaining what happens if there is no base unit to modify.

We need that somewhere anyway. Your current draft text for Cavalry assumes a base unit. Perhaps I'm missing the point. Might be one of these things best to discuss in a video call, so I'll leave this here for now. To be clear, I'm not necessarily arguing against the split Speed approach -- I'm just saying that there might be another way, and it might be neater overall even if it does cross two of our new categories.

---

> But if it counts as Y in all respects, why is it listed as X in the profile?

Having established that they really are treated as vehicles in all respects (unlike Mounted in EA), I think it is fine to list them as Vehicle/Veh in the data sheet, as long as we explain it properly.

My lingering point is only that it's just too weird to make a bald statement like "Cavalry are vehicles" -- that's like saying "your horse is a car"... clearly it isn't.
But it's fine to say something to the effect of "We treat Cavalry units exactly as Vehicle units for all purposes in the rules -- and so we identify them as Vehicles on the data sheet too". That's a pretty trivial thing to sort out, so I don't think we have any important difference of opinion here.

**Comment by IJW-Wartrader** [comment]
> > And the Data sheet modifier section would need an exception explaining what happens if there is no base unit to modify.
> 
> We need that somewhere anyway. Your current draft text for Cavalry assumes a base unit. Perhaps I'm missing the point. Might be one of these things best to discuss in a video call, so I'll leave this here for now. To be clear, I'm not necessarily arguing against the split Speed approach -- I'm just saying that there might be another way, and it might be neater overall even if it does cross two of our new categories.

Yes, we're still talking at cross-purposes. See the second post in this thread:

> Note that current Cavalry units that don't have a base unit, like Kroot Hounds, would just have a split Speed value and a unit type of VEH. They wouldn't need to list 'Cavalry' in their notes because all information would already be in the profile and there's nothing that they're being changed from.

---

> > But if it counts as Y in all respects, why is it listed as X in the profile?
> 
> Having established that they really are treated as vehicles in all respects (unlike Mounted in EA), I think it is fine to list them as Vehicle/Veh in the data sheet, as long as we explain it properly.
> 
> My lingering point is only that it's just too weird to make a bald statement like "Cavalry are vehicles" -- that's like saying "your horse is a car"... clearly it isn't.
> But it's fine to say something to the effect of "We treat Cavalry units exactly as Vehicle units for all purposes in the rules -- and so we identify them as Vehicles on the data sheet too". That's a pretty trivial thing to sort out, so I don't think we have any important difference of opinion here.

The Cavalry page currently says:

Where your unit has the {cavalry} ability, apply these changes relative to their base unit:
...
The unit type is Vehicle.

I'm confused, are you talking about that bit of rules text (which as rules text shouldn't be including background information or justifications), or about adding something to the flavour text at the top of the page?

**Comment by digi-brain** [comment]
Okay, I see why you're confused. My lingering problem with this boils down to presentation, not rules.

Basically, the the passive case 'has' and 'is' in the bullets doesn't flow well from the preceding imperative, and comes across like a statement of fact that feels odd. A change to active case will fix this I think -- I'll suggest different wording.
