### ISSUE TITLE
Movement branch plans

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#9]
Getting some notes/reminders added here where we can both see them.

* Moving through friendly units (see April playtest file).
* Not being able to move through enemy units.
* Tightening up the distinction between increased Speed and multiple moves.
* March = three moves, with road bonus checked for each move.
* Charge = one move, sometimes with a Speed increase.
* Check Hitch text for interaction with the triple move for March orders!
* Incorporate the revised Assault move logic (see April playtest file).
* When populating Skimmer, don't forget to copy the Jump Packs text and note for moving over engaged/contacted enemy units.
* War engine barging. Maybe put this in the Experimental module to start with?
* Possible page rename. The Movement phase > 'Transport' always looked a bit weird in the original GW structure, with Orks hitching a lift stuck in there, and it looks even stranger now that there are two sections within it. How about 'Transporting units' as a more generic page name that covers both abilities? And yes, I know you don't like 'ing' words... ;-) Or 'Transport and Hitch'?

**Comment by digi-brain** [comment]
All sounds good to me. Some of this stuff I did already cover but we should indeed check alongside the rest and tighten up where appropriate. Some we've covered along with the recent updates to special abilities, which we've now pushed to the master branch (especially the last point — 'Transport' is now 'Transportation', so problem solved).

---

>War engine barging. Maybe put this in the Experimental module to start with?

Yes, I agree that this is probably best -- it is a new rule, with possible unforeseen consequences. So we should probably thrash it out in the experimental section and leave it there until it has had some decent play testing and we can gauge the community reaction.

---

My only other thought at the moment is that it might make sense to break this down into several smaller issues with their own branches. Eg, war engine barging seem like a fairly discreet issue that we could work on independent of the rest.

**Comment by IJW-Wartrader** [comment]
I started a very limited branch for war engine barging, and then because that's intimately tied to assault/charge moves, I updated assault-moves-and-charges.adoc to use the updated logic from the playtest file. I think I managed to keep the 'charge move' terminology pretty well.

Unfortunately, all my attempts to rename the branch failed, as they resulted in a new branch identical to _main_ and without the changes. 🙄 However, as this branch is currently affecting only three pages (including the experimental nav.doc), we should be able to finish it off pretty quickly and not bother renaming it.

**Comment by digi-brain** [comment]
Yeah, sometimes things evolve a bit and the branch name isn't fully descriptive. I wouldn't worry too much about that — `war-engine-barging` identifies the branch by its main purpose, and we can differentiate it easily from other branches, and these are the main things.

(Odd that when you tried renaming you lost the changes though.)

For `assault-moves-and-charges.adoc`, are you making changes that are also experimental, or just clarifications that you can hook into better for barging?

**Comment by IJW-Wartrader** [comment]
My renaming attempt made a new branch with no changes and the new name, _in addition_ to the original branch!

For assault-moves-and-charges.adoc I did the full rewrite that was planned for the main movement branch. There's nothing in the barging rules that rely 100% on the changes. 

It's mostly restructuring it to match the rules logic in the playtest file, clarifying the relationship between an 'Assault move' and a 'charge move/charge', and getting the causality the right way round for charging - being able to reach contact is what makes it a charge, rather than saying that the unit is charging and then seeing if it will reach. I also added an example comparing a Space Marine unit, Assault Squad unit, and Bike unit all moving in the Assault phase.

**Comment by digi-brain** [comment]
>My renaming attempt made a new branch with no changes and the new name, in addition to the original branch!

That it resulted in a new branch doesn't surprise me, because it's a distributed version control system — Git can't control copies that *other* people might have on their local drives, so there will be some practical limitation that means it is better to make a new branch than to directly rename the existing. I guess.

That it appeared **without** any changes seems more odd — but could simply be because you hadn't committed your changes to your local instance of `war-engine-barging` and then pushed to the remote instance. It's easy to forget a step.

As for the rest, sounds good. I'll get a look when you're ready to make it into a pull request, or let me know if you'd like me to take a look and swap ideas even before then.

**Comment by IJW-Wartrader** [comment]
I was discussing the Transportation and updated assault/charge moves stuff with Richard, a local player who's not on FB, and he brought up some of the 'old' FAQs about disembarking and doubling Speed in a charge move, and how far the disembarking unit actually gets to move.

This is an extra nudge, for me, to go with your proposal to add split Speed values to all Infantry and units with Walker. As split Speed values should remove any ambiguities about subtracting for disembarking and doubling for charging.

So I'd like to start a new movement-oriented branch, to update:

- Main rules > Basics > Data sheets and characteristics. Show split Speed values for the Orks and Marines, and add an edition change note about using split Speed values for all Infantry units.
- Main rules > The Assault phase > Assault moves and charges. Remove the bullet point about Infantry doubling their Speed.
- Main rules > The Movement phase > general points about movement. Add the proposed restrictions on moving through allied units, plus associated edition change note.
- Main rules > The Movement phase > Terrain effects on movement > Dangerous terrain test. This currently says to halt the unit at the edge of the terrain, but this is not appropriate for units that were already inside the terrain.
- Main rules > The Movement phase > Terrain effects on movement > Movement on roads. Remove the text that talks about applying the 5 cm bonus to the base Speed before modification. This conflicts with the updated March text that says you make three moves, so there is no longer a 'modification'. Add text covering split Speed values, with a 5 cm bonus for the first value and 10 cm bonus for the second value. (In the original rules, Speed 10 cm Infantry on a road could charge 30 cm if they stayed on the road for the whole assault move.)
- Main rules > Common rules > Orders and conditions > Assault. This needs looking at, as it talks about _detachments_ charging, instead of _units_ charging, and about Infantry making a double move into base contact. I think this page also needs to link to Assault moves and charges.
- Special rules > Special abilities >Walker. Update to add a split Speed value, using similar text to Jump Packs and Cavalry.

**Comment by IJW-Wartrader** [comment]
> * Main rules > Common rules > Orders and conditions > Assault. This needs looking at, as it talks about _detachments_ charging, instead of _units_ charging, and about Infantry making a double move into base contact. I also propose adding a link to the Assault moves and charges page.

While I'm looking at the Orders and conditions page, the 'Advance' orders name _appears_ to be a holdover from EA content, in E40k it's usually referred to as a 'normal move' rather than a 'special move', so I did a double-take when it wasn't called 'Normal' orders.

That's not a criticism, just a comment that it looks a bit odd when coming from E40k.

**Comment by IJW-Wartrader** [comment]
The split-speed-redux-and-general-movement branch has been created, and the first commit includes the changes listed above (except Advance orders/Normal orders!).

- I had to update Jump Packs and Cavalry as well, as they were referring to a single original Speed value which no longer exists.
- Walker had to be slightly different as it's not a data sheet modifier. For now, I've added a bullet saying to add a second Speed value that's twice the normal value, but I think this can be left out and we just list them all with split Speed values.
- A bunch of pages that mention split Speed values now have the edition change note from charge moves, as a partial.
- I also added a partial for 'ganging up', spelling out that it limits the number of units that can enter base contact.
- Assault move examples 

A slight case of scope creep - as discussed earlier, I edited Cavalry to add the Armour bonus back in, including in the example. The old note about separating the Armour bonus into Armour + 1 has been removed.

TODO:

- [ ] Do a search for 'Speed value' to check that all pages that include Speed characteristics or talk about Speed values are up to date.
- [ ] Assault move examples needs another pass. I updated the profiles, but left in a 'As an Infantry unit' where it should just mention the second value.
- [ ] Types of special ability needs updating to have a split Speed value in the base unit, and to replace 'Cavalry + Armour+1' with 'Cavalry'.

**Comment by digi-brain** [comment]
Some tricky details you've spotted there, but sounds good. Nice one.

>Main rules > Common rules > Orders and conditions > Assault. This needs looking at, as it talks about detachments charging, instead of units charging...

Yes - I have a rough sense that it is okay to refer to detachments **assaulting**, **making an assault**, **joining close combat/firefight** and similar -- but not **charging**, **making a charge move** or **making an assault move**, as these are/need to be unit-specific terms.

---

>While I'm looking at the Orders and conditions page, the 'Advance' orders name appears to be a holdover from EA content, in E40k it's usually referred to as a 'normal move' rather than a 'special move', so I did a double-take when it wasn't called 'Normal' orders.
>
>That's not a criticism, just a comment that it looks a bit odd when coming from E40k.

Yes, that was another rough idea I had around the same time I called flyers aircraft. It felt to me like it'd be better with a 'proper' name, when I defined all the 'orders' and 'conditions' properly. I'm not wedded to it -- but if we're going to revert that back to 'Normal orders' then I strongly feel that we must always capitalise it and include 'orders' after, just like all the others.

---

>Walker had to be slightly different as it's not a data sheet modifier.

I'm not sure if this affects your point much, but we could (should?) of course add `Data sheet modifier' alongside it's other label, just as we have with Jump Packs.

---

>A bunch of pages that mention split Speed values now have the edition change note from charge moves, as a partial.

I've not seen it yet, but I wonder if that is really necessary after we've added it to the bit that actually explains the new split Speed values? Sounds like overkill -- but as I say, I haven't seen it, so I'm only hypothesising.

**Comment by IJW-Wartrader** [comment]
I've committed the last few tweaks, I think this is probably ready for a pull request and review.

**Comment by digi-brain** [comment]
Sounds good, go for it.

**Comment by IJW-Wartrader** [comment]
Pull request started.
